name: yamka
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-293.0.dev

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  provider: ^6.1.5
  mapbox_maps_flutter: ^2.9.1
  latlong2: ^0.9.1
  flutter_dotenv: ^5.2.1
  geolocator: ^14.0.2
  app_tracking_transparency: ^2.0.6+1
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  yandex_mobileads: ^7.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/destination-icon.png
    - assets/thunderstorm.svg
    - assets/bad-weather-icon.svg
    - assets/slippery-road-icon.svg
    - assets/flood-icon.svg
    - assets/unplowed-road-icon.svg
    - assets/fog-icon.svg
    - assets/splash-icon.svg